[workspace]
members = [
    "slime-ffi-rt",
    "slime-ffi-macros",
    "slime-ffi",
    "slime-ffi-cli",
    "slime-ffi-examples",
    "slime-ffi-test",
]

default-members = [
    "slime-ffi-rt",
    "slime-ffi-macros",
    "slime-ffi",
    "slime-ffi-cli",
]