[package]
name = "slime-ffi-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libtest-mimic = "0.6.0"

[[test]]
name = "slime-ffi-test"
path = "tests/main.rs"
harness = false